
controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController 

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0
    base_frame_id: base_link

    left_wheel_names:  ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.30
    wheel_radius: 0.10

    use_stamped_vel: false

    # odom_frame_id: odom
    # enable_odom_tf: true

    # linear:
    #   x:
    #     has_velocity_limits: true
    #     max_velocity: 1.0
    #     has_acceleration_limits: true
    #     max_acceleration: 2.0
    # angular:
    #   z:
    #     has_velocity_limits: true
    #     max_velocity: 2.0
    #     has_acceleration_limits: true
    #     max_acceleration: 4.0

    