/**:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

    diff_drive_controller:
      type: "diff_drive_controller/DiffDriveController"

diff_drive_controller:
  ros__parameters:
    left_wheel_names:  ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.30
    wheel_radius: 0.06

    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    use_stamped_vel: false

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 2.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0

    publish_rate: 50.0
